services:
  backend:
    container_name: backend
    build:
      context: .
      target: backend
    image: backend:latest
    expose:
      - "8000"
    restart: unless-stopped
    user: django
    volumes:
      - django_DI:/app/DatesIncorrectes
      - django_DAT:/app/donnees_a_traiter
      - django_doublons:/app/doublons
      - django_export:/app/export
    

  react:
    container_name: react
    build:
      context: .
      target: react
    image: react:latest
    expose:
      - "3000"
    restart: unless-stopped
    user: react
    volumes:
      - react_build:/app/build
  
  server:
    container_name: server
    build: 
      context: .
      target: server
    image: server:latest
    expose:
      - "80"
      - "3000"
    ports:
      - 8000:8000
      - 80:80
    user: nginx
    volumes:
      - react_build:/app/build
      - django_DI:/app/DatesIncorrectes
      - django_DAT:/app/donnees_a_traiter
      - django_doublons:/app/doublons
      - django_export:/app/export




volumes:
  react_build:
  django_DI:
  django_DAT:
  django_doublons:
  django_export:
